FROM ubuntu:18.04

RUN apt-get update \
    && apt-get install -y ca-certificates curl apt-transport-https lsb-release gnupg \
    && curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | tee /etc/apt/trusted.gpg.d/microsoft.asc.gpg > /dev/null \
    && echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $(lsb_release -cs) main" |tee /etc/apt/sources.list.d/azure-cli.list \
    && sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-$(lsb_release -cs)-prod $(lsb_release -cs) main" > /etc/apt/sources.list.d/dotnetdev.list' \
    && apt-get update \
    && apt-get install -y azure-cli azure-functions-core-tools

ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT 1
ENV FUNCTIONS_CORE_TOOLS_TELEMETRY_OPTOUT 1

RUN useradd \
        --create-home \
        --shell /bin/bash \
        docker

RUN chown -R docker:docker /home/docker

USER docker

WORKDIR /home/docker

CMD /bin/bash
